### ISSUE TITLE
Error setting up workbench

### ISSUE THREAD

**Issue by humnrdble** [METR/task-template#3]
Hi,

I'm currently implementing a task proposal you accepted.
I run into problems trying to use the workbench on codespaces.

`/workspaces/task-template/workbench (main) $ npm run task -- ../my_task/ addition`

[...]

```
 => => naming to docker.io/library/metr-task-standard-image-my_task-addition-1948150149                              0.0s
 === Starting container === 
835748e8fd3d2102eb7ac5cf6c78e567287e5b8850a4b907725b18a1db3aa0d0

/workspaces/task-template/workbench/drivers/DriverImpl.ts:52
  throw new Error(`File not found: ${relativePath}`)
        ^
Error: File not found: ./task-standard/drivers/taskhelper.py
    at readFromAncestor (/workspaces/task-template/workbench/drivers/DriverImpl.ts:52:9)
    at getDefaultTaskHelperCode (/workspaces/task-template/workbench/drivers/DriverImpl.ts:34:22)
    at new _DriverImpl (/workspaces/task-template/workbench/drivers/DriverImpl.ts:71:39)
    at getDriver (/workspaces/task-template/workbench/src/src/task-environment/getDriver.ts:5:10)
    at createTaskEnvironment (/workspaces/task-template/workbench/src/src/task-environment/createTaskEnvironment.ts:222:18)
    at main (/workspaces/task-template/workbench/src/src/task.ts:13:70)
    at cli (/workspaces/task-template/workbench/src/src/task.ts:75:3)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

A similar error occurs when subsequently running `/workspaces/task-template/workbench (main) $ npm run test -- ../my_task/ addition my_task_test`

(This problem occurs both when starting the codespace on your repository and when first creating a repository using the "use this template button" and then running codespaces.)

**Comment by pipmc** [comment]
Thanks for this. I've submitted a PR to the upstream repo for the Task Standard and when it's approved the changes should be pushed to this repo.
